# Generated by Django 3.2.9 on 2021-11-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment_text',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
